"""
Bot Utilities Module
Helper functions and utilities

Utils:
- keyboards: Inline keyboard builders
- messages: Vietnamese message templates
- validators: Input validation
- formatters: Output formatting
"""

from .messages import (
    # Command responses
    MSG_START,
    MSG_HELP,
    MSG_INFO,
    # Task messages
    MSG_TASK_CREATED,
    MSG_TASK_ASSIGNED,
    MSG_TASK_RECEIVED,
    MSG_TASK_COMPLETED,
    MSG_TASK_DELETED,
    MSG_TASK_RESTORED,
    MSG_TASK_DETAIL,
    MSG_TASK_LIST,
    MSG_TASK_LIST_EMPTY,
    MSG_TASK_LIST_ITEM,
    # Reminder messages
    MSG_REMINDER_24H,
    MSG_REMINDER_1H,
    MSG_REMINDER_OVERDUE,
    # Error messages
    ERR_NO_PERMISSION,
    ERR_NOT_FOUND,
    ERR_TASK_NOT_FOUND,
    ERR_USER_NOT_FOUND,
    ERR_INVALID_TIME,
    ERR_NO_CONTENT,
    ERR_NO_ASSIGNEE,
    ERR_GROUP_ONLY,
    ERR_PRIVATE_ONLY,
    ERR_UNDO_EXPIRED,
    ERR_ALREADY_COMPLETED,
    ERR_DATABASE,
    # Labels
    STATUS_PENDING,
    STATUS_IN_PROGRESS,
    STATUS_COMPLETED,
    STATUS_CANCELLED,
    PRIORITY_LOW,
    PRIORITY_NORMAL,
    PRIORITY_HIGH,
    PRIORITY_URGENT,
    # Icons
    ICON_PENDING,
    ICON_IN_PROGRESS,
    ICON_COMPLETED,
    ICON_OVERDUE,
    ICON_URGENT,
    ICON_HIGH,
)

from .formatters import (
    format_status,
    format_priority,
    get_status_icon,
    format_datetime,
    format_task_detail,
    format_task_list,
    truncate,
    escape_markdown,
    progress_bar,
    format_stats_overview,
    format_weekly_report,
    format_monthly_report,
    mention_user,
    mention_user_html,
)

from .keyboards import (
    task_actions_keyboard,
    task_detail_keyboard,
    task_category_keyboard,
    progress_keyboard,
    undo_keyboard,
    pagination_keyboard,
    task_list_with_pagination,
    priority_keyboard,
    confirm_keyboard,
    edit_menu_keyboard,
    edit_priority_keyboard,
    # Wizard keyboards
    wizard_deadline_keyboard,
    wizard_assignee_keyboard,
    wizard_priority_keyboard,
    wizard_confirm_keyboard,
    wizard_cancel_keyboard,
    task_type_filter_keyboard,
)

from .validators import (
    extract_mentions,
    validate_task_content,
    validate_priority,
    validate_status,
    validate_progress,
    parse_task_command,
    is_valid_public_id,
    sanitize_html,
)

__all__ = [
    # Messages
    "MSG_START",
    "MSG_HELP",
    "MSG_INFO",
    "MSG_TASK_CREATED",
    "MSG_TASK_ASSIGNED",
    "MSG_TASK_RECEIVED",
    "MSG_TASK_COMPLETED",
    "MSG_TASK_DELETED",
    "MSG_TASK_RESTORED",
    "MSG_TASK_DETAIL",
    "MSG_TASK_LIST",
    "MSG_TASK_LIST_EMPTY",
    "MSG_TASK_LIST_ITEM",
    "MSG_REMINDER_24H",
    "MSG_REMINDER_1H",
    "MSG_REMINDER_OVERDUE",
    "ERR_NO_PERMISSION",
    "ERR_NOT_FOUND",
    "ERR_TASK_NOT_FOUND",
    "ERR_USER_NOT_FOUND",
    "ERR_INVALID_TIME",
    "ERR_NO_CONTENT",
    "ERR_NO_ASSIGNEE",
    "ERR_GROUP_ONLY",
    "ERR_PRIVATE_ONLY",
    "ERR_UNDO_EXPIRED",
    "ERR_ALREADY_COMPLETED",
    "ERR_DATABASE",
    "STATUS_PENDING",
    "STATUS_IN_PROGRESS",
    "STATUS_COMPLETED",
    "STATUS_CANCELLED",
    "PRIORITY_LOW",
    "PRIORITY_NORMAL",
    "PRIORITY_HIGH",
    "PRIORITY_URGENT",
    "ICON_PENDING",
    "ICON_IN_PROGRESS",
    "ICON_COMPLETED",
    "ICON_OVERDUE",
    "ICON_URGENT",
    "ICON_HIGH",
    # Formatters
    "format_status",
    "format_priority",
    "get_status_icon",
    "format_datetime",
    "format_task_detail",
    "format_task_list",
    "truncate",
    "escape_markdown",
    "progress_bar",
    "format_stats_overview",
    "format_weekly_report",
    "format_monthly_report",
    "mention_user",
    "mention_user_html",
    # Keyboards
    "task_actions_keyboard",
    "task_detail_keyboard",
    "task_category_keyboard",
    "progress_keyboard",
    "undo_keyboard",
    "pagination_keyboard",
    "task_list_with_pagination",
    "priority_keyboard",
    "confirm_keyboard",
    "edit_menu_keyboard",
    "edit_priority_keyboard",
    # Wizard keyboards
    "wizard_deadline_keyboard",
    "wizard_assignee_keyboard",
    "wizard_priority_keyboard",
    "wizard_confirm_keyboard",
    "wizard_cancel_keyboard",
    "task_type_filter_keyboard",
    # Validators
    "extract_mentions",
    "validate_task_content",
    "validate_priority",
    "validate_status",
    "validate_progress",
    "parse_task_command",
    "is_valid_public_id",
    "sanitize_html",
]
